name: my_bridge
topics:
  turtle1/rotate_absolute/_action/feedback:
    type: example_interfaces/msg/Float32
    from_domain: 1
    to_domain: 2
  result:
    type: example_interfaces/msg/Float32MultiArray
    from_domain: 1
    to_domain: 2
  goal:
    type: example_interfaces/msg/Float32MultiArray
    from_domain: 2
    to_domain: 1
