drobot_motor:
  ros__parameters:
    robot_coordinates:
      robot1: [0.0, 2.5, 0.0]
      robot2: [0.0, 1.5, 0.0]
      robot3: [0.0, 0.3, 0.0]
    kiosk_coordinates:
      kiosk11: [0.3, 3.0, 80.0]
      kiosk12: [1.15, 2.8, 80.0]
      kiosk21: [1.15, 0.5, -80.0]
      kiosk22: [0.3, 0.5, -80.0]
    store_coordinates:
      store11: [1.3, 2.6, 0.0]
      store12: [1.3, 1.7, 0.0]
      store21: [1.3, 1.3, 0.0]
      store22: [1.3, 0.3, 0.0]
    waypoints:
      way1: [0.3, 2.6, 0.0]
      way2: [0.3, 1.5, -80.0]
      way3: [0.3, 0.3, -80.0]
      way4: [1.15, 0.3, 160.0]
      way5: [1.15, 1.5, 160.0]
      way6: [1.15, 2.5, 80.0]
