drobot_motor:
  ros__parameters:
    way1:
      - [0.5, 2.6, 0]
      - [0.5, 2.6, 80]
      - [0.5, 2.6, -80]
      - [0.5, 2.6, 160]
    way2:
      - [0.5, 1.5, 0]
      - [0.5, 1.5, 80]
      - [0.5, 1.5, -80]
      - [0.5, 1.5, 160]
    way3:
      - [0.5, 0.3, 0]
      - [0.5, 0.3, 80]
      - [0.5, 0.3, -80]
      - [0.5, 0.3, 160]
    way4:
      - [1.15, 0.3, 0]
      - [1.15, 0.3, 80]
      - [1.15, 0.3, -80]
      - [1.15, 0.3, 160]
    way5:
      - [1.15, 1.3, 0]
      - [1.15, 1.3, 80]
      - [1.15, 1.3, -80]
      - [1.15, 1.3, 160]
    way6:
      - [1.15, 1.8, 0]
      - [1.15, 1.8, 80]
      - [1.15, 1.8, -80]
      - [1.15, 1.8, 160]
    way7:
      - [1.15, 2.5, 0]
      - [1.15, 2.5, 80]
      - [1.15, 2.5, -80]
      - [1.15, 2.5, 160]
    robot_coordinates:
      robot1: [-0.1, 2.5, 0]
      robot2: [-0.1, 1.5, 0.0]
      robot3: [-0.1, 0.3, 0.0]
    kiosk_coordinates:
      kiosk11: [0.3, 3.2, 80]
      kiosk12: [1.15, 2.8, 80]
      kiosk21: [1.15, 0.5, -80]
      kiosk22: [0.3, 0.5, -80]
    store_coordinates:
      store11: [1.7, 2.8, 160]
      store12: [1.7, 1.7, 160]
      store21: [1.7, 1.3, 160]
      store22: [1.7, 0.3, 160]